insert into przedmiot (id_p, nazwa, min_ilosc) values (65, 'in', 4);
insert into przedmiot (id_p, nazwa, min_ilosc) values (20, 'morbi non', 5);
insert into przedmiot (id_p, nazwa, min_ilosc) values (12, 'id sapien', 6);
insert into przedmiot (id_p, nazwa, min_ilosc) values (81, 'vel', 4);
insert into przedmiot (id_p, nazwa, min_ilosc) values (55, 'aliquet', 5);
insert into przedmiot (id_p, nazwa, min_ilosc) values (13, 'nunc nisl', 1);
insert into przedmiot (id_p, nazwa, min_ilosc) values (41, 'tellus nulla', 1);
insert into przedmiot (id_p, nazwa, min_ilosc) values (40, 'posuere metus', 4);
insert into przedmiot (id_p, nazwa, min_ilosc) values (13, 'convallis morbi', 9);
insert into przedmiot (id_p, nazwa, min_ilosc) values (44, 'mattis pulvinar', 6);
insert into przedmiot (id_p, nazwa, min_ilosc) values (25, 'risus', 5);
insert into przedmiot (id_p, nazwa, min_ilosc) values (13, 'sodales', 4);
insert into przedmiot (id_p, nazwa, min_ilosc) values (53, 'in blandit', 3);
insert into przedmiot (id_p, nazwa, min_ilosc) values (59, 'lobortis', 3);
insert into przedmiot (id_p, nazwa, min_ilosc) values (30, 'lectus in', 2);
insert into przedmiot (id_p, nazwa, min_ilosc) values (36, 'justo', 2);
insert into przedmiot (id_p, nazwa, min_ilosc) values (93, 'erat', 4);
insert into przedmiot (id_p, nazwa, min_ilosc) values (56, 'maecenas tristique', 6);
insert into przedmiot (id_p, nazwa, min_ilosc) values (96, 'varius nulla', 9);
insert into przedmiot (id_p, nazwa, min_ilosc) values (55, 'sit amet', 4);
insert into przedmiot (id_p, nazwa, min_ilosc) values (59, 'nonummy', 9);
insert into przedmiot (id_p, nazwa, min_ilosc) values (7, 'elementum', 4);
insert into przedmiot (id_p, nazwa, min_ilosc) values (30, 'mollis molestie', 4);
insert into przedmiot (id_p, nazwa, min_ilosc) values (75, 'est', 2);
insert into przedmiot (id_p, nazwa, min_ilosc) values (8, 'neque', 2);
insert into przedmiot (id_p, nazwa, min_ilosc) values (71, 'nulla', 7);
insert into przedmiot (id_p, nazwa, min_ilosc) values (71, 'sit', 8);
insert into przedmiot (id_p, nazwa, min_ilosc) values (95, 'curabitur', 4);
insert into przedmiot (id_p, nazwa, min_ilosc) values (81, 'laoreet', 7);
insert into przedmiot (id_p, nazwa, min_ilosc) values (55, 'dictumst aliquam', 4);
insert into przedmiot (id_p, nazwa, min_ilosc) values (57, 'molestie hendrerit', 3);
insert into przedmiot (id_p, nazwa, min_ilosc) values (83, 'suspendisse potenti', 3);
insert into przedmiot (id_p, nazwa, min_ilosc) values (23, 'nulla nunc', 9);
insert into przedmiot (id_p, nazwa, min_ilosc) values (43, 'mauris', 3);
insert into przedmiot (id_p, nazwa, min_ilosc) values (35, 'accumsan', 6);
insert into przedmiot (id_p, nazwa, min_ilosc) values (99, 'amet', 3);
insert into przedmiot (id_p, nazwa, min_ilosc) values (71, 'pellentesque', 9);
insert into przedmiot (id_p, nazwa, min_ilosc) values (75, 'vestibulum', 3);
insert into przedmiot (id_p, nazwa, min_ilosc) values (78, 'pellentesque', 2);
insert into przedmiot (id_p, nazwa, min_ilosc) values (16, 'in', 4);
insert into przedmiot (id_p, nazwa, min_ilosc) values (71, 'natoque penatibus', 2);
insert into przedmiot (id_p, nazwa, min_ilosc) values (65, 'turpis sed', 8);
insert into przedmiot (id_p, nazwa, min_ilosc) values (53, 'risus', 2);
insert into przedmiot (id_p, nazwa, min_ilosc) values (12, 'nonummy', 2);
insert into przedmiot (id_p, nazwa, min_ilosc) values (7, 'interdum eu', 3);
insert into przedmiot (id_p, nazwa, min_ilosc) values (46, 'et ultrices', 5);
insert into przedmiot (id_p, nazwa, min_ilosc) values (27, 'dolor morbi', 3);
insert into przedmiot (id_p, nazwa, min_ilosc) values (28, 'lorem integer', 8);
insert into przedmiot (id_p, nazwa, min_ilosc) values (49, 'in lacus', 3);
insert into przedmiot (id_p, nazwa, min_ilosc) values (18, 'pulvinar', 1);
insert into przedmiot (id_p, nazwa, min_ilosc) values (60, 'semper sapien', 3);
insert into przedmiot (id_p, nazwa, min_ilosc) values (71, 'varius nulla', 4);
insert into przedmiot (id_p, nazwa, min_ilosc) values (77, 'primis', 7);
insert into przedmiot (id_p, nazwa, min_ilosc) values (26, 'donec odio', 3);
insert into przedmiot (id_p, nazwa, min_ilosc) values (25, 'ligula', 5);
insert into przedmiot (id_p, nazwa, min_ilosc) values (1, 'cubilia', 6);
insert into przedmiot (id_p, nazwa, min_ilosc) values (33, 'justo', 8);
insert into przedmiot (id_p, nazwa, min_ilosc) values (0, 'quisque erat', 9);
insert into przedmiot (id_p, nazwa, min_ilosc) values (11, 'in imperdiet', 2);
insert into przedmiot (id_p, nazwa, min_ilosc) values (73, 'vulputate', 6);
insert into przedmiot (id_p, nazwa, min_ilosc) values (75, 'in faucibus', 8);
insert into przedmiot (id_p, nazwa, min_ilosc) values (81, 'ac nulla', 5);
insert into przedmiot (id_p, nazwa, min_ilosc) values (22, 'eu felis', 8);
insert into przedmiot (id_p, nazwa, min_ilosc) values (51, 'nam', 2);
insert into przedmiot (id_p, nazwa, min_ilosc) values (84, 'curae duis', 7);
insert into przedmiot (id_p, nazwa, min_ilosc) values (23, 'convallis', 8);
insert into przedmiot (id_p, nazwa, min_ilosc) values (45, 'sed', 8);
insert into przedmiot (id_p, nazwa, min_ilosc) values (25, 'quis', 3);
insert into przedmiot (id_p, nazwa, min_ilosc) values (66, 'ut', 3);
insert into przedmiot (id_p, nazwa, min_ilosc) values (36, 'massa id', 4);
insert into przedmiot (id_p, nazwa, min_ilosc) values (72, 'aliquam', 8);
insert into przedmiot (id_p, nazwa, min_ilosc) values (49, 'sit', 1);
insert into przedmiot (id_p, nazwa, min_ilosc) values (85, 'lacus at', 8);
insert into przedmiot (id_p, nazwa, min_ilosc) values (29, 'sit amet', 6);
insert into przedmiot (id_p, nazwa, min_ilosc) values (94, 'velit', 8);
insert into przedmiot (id_p, nazwa, min_ilosc) values (50, 'sed', 4);
insert into przedmiot (id_p, nazwa, min_ilosc) values (5, 'a', 2);
insert into przedmiot (id_p, nazwa, min_ilosc) values (94, 'eleifend', 3);
insert into przedmiot (id_p, nazwa, min_ilosc) values (44, 'eget massa', 1);
insert into przedmiot (id_p, nazwa, min_ilosc) values (60, 'odio', 7);
insert into przedmiot (id_p, nazwa, min_ilosc) values (37, 'dignissim vestibulum', 8);
insert into przedmiot (id_p, nazwa, min_ilosc) values (43, 'at turpis', 8);
insert into przedmiot (id_p, nazwa, min_ilosc) values (9, 'est lacinia', 3);
insert into przedmiot (id_p, nazwa, min_ilosc) values (58, 'sapien sapien', 3);
insert into przedmiot (id_p, nazwa, min_ilosc) values (3, 'risus auctor', 2);
insert into przedmiot (id_p, nazwa, min_ilosc) values (90, 'morbi non', 7);
insert into przedmiot (id_p, nazwa, min_ilosc) values (82, 'dapibus augue', 5);
insert into przedmiot (id_p, nazwa, min_ilosc) values (39, 'ante ipsum', 9);
insert into przedmiot (id_p, nazwa, min_ilosc) values (57, 'cum', 9);
insert into przedmiot (id_p, nazwa, min_ilosc) values (16, 'ipsum', 3);
insert into przedmiot (id_p, nazwa, min_ilosc) values (41, 'curae nulla', 2);
insert into przedmiot (id_p, nazwa, min_ilosc) values (94, 'velit', 4);
insert into przedmiot (id_p, nazwa, min_ilosc) values (85, 'nunc proin', 9);
insert into przedmiot (id_p, nazwa, min_ilosc) values (29, 'nonummy integer', 7);
insert into przedmiot (id_p, nazwa, min_ilosc) values (31, 'faucibus', 8);
insert into przedmiot (id_p, nazwa, min_ilosc) values (24, 'urna ut', 1);
insert into przedmiot (id_p, nazwa, min_ilosc) values (58, 'at nunc', 1);
insert into przedmiot (id_p, nazwa, min_ilosc) values (91, 'rutrum', 7);
insert into przedmiot (id_p, nazwa, min_ilosc) values (63, 'ac', 2);
insert into przedmiot (id_p, nazwa, min_ilosc) values (17, 'justo', 3);
insert into przedmiot (id_p, nazwa, min_ilosc) values (11, 'quis', 1);
insert into przedmiot (id_p, nazwa, min_ilosc) values (45, 'luctus', 8);
insert into przedmiot (id_p, nazwa, min_ilosc) values (78, 'nullam porttitor', 5);
insert into przedmiot (id_p, nazwa, min_ilosc) values (93, 'primis', 1);
insert into przedmiot (id_p, nazwa, min_ilosc) values (65, 'eget', 3);
insert into przedmiot (id_p, nazwa, min_ilosc) values (46, 'posuere', 3);
insert into przedmiot (id_p, nazwa, min_ilosc) values (90, 'eleifend', 6);
insert into przedmiot (id_p, nazwa, min_ilosc) values (15, 'penatibus et', 9);
insert into przedmiot (id_p, nazwa, min_ilosc) values (87, 'ante ipsum', 3);
insert into przedmiot (id_p, nazwa, min_ilosc) values (51, 'ipsum ac', 7);
insert into przedmiot (id_p, nazwa, min_ilosc) values (29, 'urna', 4);
insert into przedmiot (id_p, nazwa, min_ilosc) values (69, 'volutpat', 1);
insert into przedmiot (id_p, nazwa, min_ilosc) values (73, 'tincidunt eu', 3);
insert into przedmiot (id_p, nazwa, min_ilosc) values (25, 'consequat', 3);
insert into przedmiot (id_p, nazwa, min_ilosc) values (29, 'mattis egestas', 5);
insert into przedmiot (id_p, nazwa, min_ilosc) values (9, 'in', 1);
insert into przedmiot (id_p, nazwa, min_ilosc) values (83, 'primis', 7);
insert into przedmiot (id_p, nazwa, min_ilosc) values (10, 'convallis', 8);
insert into przedmiot (id_p, nazwa, min_ilosc) values (37, 'sapien', 9);
insert into przedmiot (id_p, nazwa, min_ilosc) values (63, 'at', 3);
insert into przedmiot (id_p, nazwa, min_ilosc) values (57, 'ipsum primis', 4);
insert into przedmiot (id_p, nazwa, min_ilosc) values (58, 'diam cras', 5);
insert into przedmiot (id_p, nazwa, min_ilosc) values (60, 'sagittis', 3);
insert into przedmiot (id_p, nazwa, min_ilosc) values (25, 'non mauris', 3);
insert into przedmiot (id_p, nazwa, min_ilosc) values (80, 'id massa', 9);
insert into przedmiot (id_p, nazwa, min_ilosc) values (33, 'quis', 1);
insert into przedmiot (id_p, nazwa, min_ilosc) values (79, 'in quam', 4);
insert into przedmiot (id_p, nazwa, min_ilosc) values (28, 'vulputate', 8);
insert into przedmiot (id_p, nazwa, min_ilosc) values (37, 'quam', 8);
insert into przedmiot (id_p, nazwa, min_ilosc) values (1, 'ipsum', 9);
insert into przedmiot (id_p, nazwa, min_ilosc) values (48, 'aliquam', 2);
insert into przedmiot (id_p, nazwa, min_ilosc) values (62, 'integer', 1);
insert into przedmiot (id_p, nazwa, min_ilosc) values (1, 'ante ipsum', 2);
insert into przedmiot (id_p, nazwa, min_ilosc) values (75, 'erat', 1);
insert into przedmiot (id_p, nazwa, min_ilosc) values (45, 'sapien dignissim', 5);
insert into przedmiot (id_p, nazwa, min_ilosc) values (35, 'commodo', 4);
insert into przedmiot (id_p, nazwa, min_ilosc) values (47, 'proin leo', 5);
insert into przedmiot (id_p, nazwa, min_ilosc) values (51, 'rutrum', 1);
insert into przedmiot (id_p, nazwa, min_ilosc) values (81, 'sit', 7);
insert into przedmiot (id_p, nazwa, min_ilosc) values (22, 'faucibus orci', 9);
insert into przedmiot (id_p, nazwa, min_ilosc) values (11, 'sapien ut', 7);
insert into przedmiot (id_p, nazwa, min_ilosc) values (31, 'dui', 1);
insert into przedmiot (id_p, nazwa, min_ilosc) values (1, 'dui luctus', 2);
insert into przedmiot (id_p, nazwa, min_ilosc) values (79, 'interdum mauris', 1);
insert into przedmiot (id_p, nazwa, min_ilosc) values (65, 'imperdiet', 7);
insert into przedmiot (id_p, nazwa, min_ilosc) values (47, 'tincidunt', 4);
insert into przedmiot (id_p, nazwa, min_ilosc) values (70, 'tincidunt nulla', 9);
insert into przedmiot (id_p, nazwa, min_ilosc) values (29, 'tempus', 3);
insert into przedmiot (id_p, nazwa, min_ilosc) values (58, 'neque duis', 8);
insert into przedmiot (id_p, nazwa, min_ilosc) values (40, 'morbi porttitor', 1);
insert into przedmiot (id_p, nazwa, min_ilosc) values (86, 'ligula', 5);
insert into przedmiot (id_p, nazwa, min_ilosc) values (60, 'sed sagittis', 8);
insert into przedmiot (id_p, nazwa, min_ilosc) values (74, 'ultrices', 3);
insert into przedmiot (id_p, nazwa, min_ilosc) values (22, 'ac', 9);
insert into przedmiot (id_p, nazwa, min_ilosc) values (92, 'id', 7);
insert into przedmiot (id_p, nazwa, min_ilosc) values (80, 'et ultrices', 4);
insert into przedmiot (id_p, nazwa, min_ilosc) values (53, 'ante vestibulum', 8);
insert into przedmiot (id_p, nazwa, min_ilosc) values (61, 'et commodo', 6);
insert into przedmiot (id_p, nazwa, min_ilosc) values (74, 'pede', 9);
insert into przedmiot (id_p, nazwa, min_ilosc) values (6, 'ac nibh', 4);
insert into przedmiot (id_p, nazwa, min_ilosc) values (4, 'in', 6);
insert into przedmiot (id_p, nazwa, min_ilosc) values (76, 'maecenas rhoncus', 5);
insert into przedmiot (id_p, nazwa, min_ilosc) values (96, 'sit', 1);
insert into przedmiot (id_p, nazwa, min_ilosc) values (86, 'suscipit ligula', 1);
insert into przedmiot (id_p, nazwa, min_ilosc) values (13, 'consequat', 7);
insert into przedmiot (id_p, nazwa, min_ilosc) values (41, 'metus sapien', 1);
insert into przedmiot (id_p, nazwa, min_ilosc) values (85, 'interdum eu', 9);
insert into przedmiot (id_p, nazwa, min_ilosc) values (74, 'diam', 2);
insert into przedmiot (id_p, nazwa, min_ilosc) values (57, 'ligula', 7);
insert into przedmiot (id_p, nazwa, min_ilosc) values (79, 'nibh ligula', 7);
insert into przedmiot (id_p, nazwa, min_ilosc) values (43, 'sit amet', 3);
insert into przedmiot (id_p, nazwa, min_ilosc) values (51, 'enim sit', 2);
insert into przedmiot (id_p, nazwa, min_ilosc) values (69, 'nec nisi', 6);
insert into przedmiot (id_p, nazwa, min_ilosc) values (46, 'ligula vehicula', 8);
insert into przedmiot (id_p, nazwa, min_ilosc) values (59, 'maecenas', 3);
insert into przedmiot (id_p, nazwa, min_ilosc) values (47, 'nunc rhoncus', 6);
insert into przedmiot (id_p, nazwa, min_ilosc) values (94, 'tincidunt', 2);
insert into przedmiot (id_p, nazwa, min_ilosc) values (12, 'a', 4);
insert into przedmiot (id_p, nazwa, min_ilosc) values (52, 'habitasse platea', 3);
insert into przedmiot (id_p, nazwa, min_ilosc) values (11, 'mi', 7);
insert into przedmiot (id_p, nazwa, min_ilosc) values (19, 'ac lobortis', 5);
insert into przedmiot (id_p, nazwa, min_ilosc) values (40, 'nibh ligula', 5);
insert into przedmiot (id_p, nazwa, min_ilosc) values (51, 'id pretium', 7);
insert into przedmiot (id_p, nazwa, min_ilosc) values (60, 'sed tincidunt', 4);
insert into przedmiot (id_p, nazwa, min_ilosc) values (53, 'blandit', 1);
insert into przedmiot (id_p, nazwa, min_ilosc) values (35, 'iaculis diam', 7);
insert into przedmiot (id_p, nazwa, min_ilosc) values (52, 'fusce consequat', 4);
insert into przedmiot (id_p, nazwa, min_ilosc) values (28, 'pellentesque volutpat', 3);
insert into przedmiot (id_p, nazwa, min_ilosc) values (18, 'at', 8);
insert into przedmiot (id_p, nazwa, min_ilosc) values (31, 'ante', 2);
insert into przedmiot (id_p, nazwa, min_ilosc) values (84, 'augue vestibulum', 1);
insert into przedmiot (id_p, nazwa, min_ilosc) values (99, 'duis', 1);
insert into przedmiot (id_p, nazwa, min_ilosc) values (98, 'eros vestibulum', 6);
insert into przedmiot (id_p, nazwa, min_ilosc) values (41, 'hac', 7);
insert into przedmiot (id_p, nazwa, min_ilosc) values (19, 'sapien urna', 1);
insert into przedmiot (id_p, nazwa, min_ilosc) values (31, 'in', 7);
insert into przedmiot (id_p, nazwa, min_ilosc) values (39, 'ut suscipit', 8);
insert into przedmiot (id_p, nazwa, min_ilosc) values (8, 'tincidunt nulla', 6);
insert into przedmiot (id_p, nazwa, min_ilosc) values (87, 'bibendum', 8);
insert into przedmiot (id_p, nazwa, min_ilosc) values (75, 'morbi non', 7);
