insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (77, 'magna at nunc', 0, 'turpis', 'btreend0');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (61, 'orci', 22, 'volutpat', 'cneely1');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (91, 'congue', 11, 'penatibus', 'dcamp2');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (48, 'quam turpis', 9, 'nonummy', 'ddrinkhill3');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (91, 'ut volutpat', 4, 'enim', 'yheisman4');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (57, 'purus sit amet', 37, 'felis', 'kdanieli5');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (74, 'vel', 31, 'et', 'leidler6');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (72, 'lacus at', 38, 'sit', 'bubsdall7');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (80, 'magnis', 9, 'at', 'satheis8');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (52, 'eleifend luctus ultricies', 1, 'augue', 'atreadway9');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (71, 'sapien sapien', 29, 'hac', 'tpranglea');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (52, 'vestibulum proin eu', 7, 'id', 'ahowsdenb');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (96, 'odio donec', 23, 'mauris', 'hchippsc');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (34, 'nec condimentum', 44, 'pede', 'mpretord');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (38, 'eros viverra eget', 13, 'urna', 'abrightmane');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (83, 'iaculis congue vivamus', 42, 'justo', 'credbournf');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (72, 'eget vulputate', 36, 'quisque', 'lpickervanceg');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (48, 'sit', 48, 'nibh', 'kjozwikh');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (71, 'posuere metus vitae', 41, 'id', 'ttompkini');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (10, 'sapien arcu', 11, 'sit', 'sgartsidej');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (32, 'neque', 38, 'dui', 'lpeckk');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (63, 'pellentesque quisque', 47, 'iaculis', 'grenyardl');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (14, 'blandit nam nulla', 0, 'integer', 'mcrellinm');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (46, 'molestie lorem quisque', 27, 'non', 'mmasdingn');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (76, 'in', 17, 'risus', 'mhardingeo');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (44, 'nisl duis bibendum', 12, 'pede', 'ubohlerp');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (12, 'nunc donec', 43, 'nascetur', 'mlyalq');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (8, 'felis eu sapien', 31, 'adipiscing', 'sdorwoodr');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (54, 'lorem', 24, 'eget', 'cchimientis');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (3, 'a ipsum', 37, 'in', 'jgeistt');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (86, 'potenti', 36, 'molestie', 'awantu');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (38, 'fusce posuere felis', 7, 'hendrerit', 'awestneyv');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (62, 'sem', 27, 'rutrum', 'tbreedw');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (100, 'adipiscing', 50, 'faucibus', 'pphlippsenx');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (84, 'augue vestibulum', 23, 'convallis', 'tdevonshirey');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (20, 'hac habitasse platea', 4, 'non', 'hronanz');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (68, 'magna', 35, 'euismod', 'gbramich10');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (51, 'vehicula', 10, 'diam', 'gahren11');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (43, 'vitae', 32, 'quisque', 'tbarkworth12');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (95, 'penatibus', 42, 'ante', 'ewoolmer13');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (45, 'platea dictumst', 25, 'nascetur', 'cswetmore14');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (2, 'vitae', 38, 'natoque', 'bmenier15');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (14, 'odio condimentum id', 27, 'non', 'aagostini16');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (63, 'erat', 18, 'odio', 'lkeenleyside17');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (86, 'leo', 0, 'luctus', 'nodoherty18');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (50, 'amet sem', 39, 'tincidunt', 'aschreiner19');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (66, 'eget nunc', 33, 'donec', 'tkleinfeld1a');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (17, 'ante', 26, 'nunc', 'ihelm1b');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (80, 'gravida nisi', 19, 'eu', 'dtrippack1c');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (64, 'erat vestibulum sed', 9, 'orci', 'zrosencwaig1d');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (64, 'diam nam tristique', 50, 'nec', 'tsammars1e');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (4, 'consequat', 27, 'nibh', 'tkleeborn1f');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (95, 'sit amet', 4, 'lacus', 'bkelinge1g');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (40, 'nibh', 41, 'nascetur', 'jdossett1h');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (58, 'habitasse', 26, 'id', 'jrosengart1i');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (29, 'lobortis', 17, 'pellentesque', 'cascraft1j');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (43, 'imperdiet sapien', 20, 'orci', 'kdanjoie1k');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (54, 'risus praesent lectus', 23, 'vehicula', 'bdeer1l');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (7, 'lobortis', 37, 'tempor', 'srobottom1m');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (9, 'libero convallis', 28, 'sit', 'tdonoher1n');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (56, 'erat volutpat in', 12, 'etiam', 'dallonby1o');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (61, 'eu tincidunt in', 13, 'massa', 'cchaldecott1p');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (77, 'vulputate ut ultrices', 39, 'cum', 'rferreri1q');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (73, 'natoque penatibus', 17, 'at', 'csimkins1r');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (53, 'erat', 39, 'eleifend', 'eglasson1s');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (50, 'placerat', 14, 'eget', 'jjakubovicz1t');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (44, 'maecenas ut massa', 45, 'dis', 'khalbard1u');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (27, 'lorem id', 27, 'habitasse', 'osarginson1v');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (80, 'cras', 40, 'orci', 'gpennick1w');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (60, 'bibendum', 3, 'sed', 'jjeynes1x');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (34, 'at', 44, 'ut', 'rtomczak1y');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (93, 'lobortis', 9, 'augue', 'rknottley1z');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (45, 'amet nulla quisque', 31, 'nisl', 'lgravie20');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (62, 'mi integer', 49, 'non', 'amackellar21');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (21, 'leo pellentesque ultrices', 3, 'suspendisse', 'wlages22');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (70, 'faucibus orci luctus', 25, 'luctus', 'vheilds23');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (37, 'neque duis bibendum', 8, 'nec', 'acord24');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (50, 'integer pede justo', 0, 'ac', 'npaterson25');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (40, 'nibh in', 34, 'est', 'amavin26');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (91, 'morbi ut odio', 46, 'eleifend', 'acund27');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (25, 'rutrum rutrum neque', 6, 'semper', 'aandrusov28');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (85, 'nisi', 31, 'tincidunt', 'keverit29');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (47, 'curabitur in libero', 2, 'augue', 'dgillice2a');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (60, 'est donec', 7, 'morbi', 'pbilles2b');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (53, 'metus', 27, 'mi', 'ptrout2c');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (43, 'nunc', 0, 'faucibus', 'dchurly2d');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (32, 'interdum eu tincidunt', 15, 'massa', 'mferrarone2e');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (30, 'integer', 15, 'nulla', 'dleyninye2f');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (9, 'vitae consectetuer eget', 14, 'ridiculus', 'rattock2g');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (9, 'rutrum at lorem', 10, 'lacus', 'adainty2h');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (25, 'condimentum curabitur', 38, 'sem', 'gbassett2i');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (63, 'vulputate', 38, 'lorem', 'oveivers2j');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (65, 'id nulla ultrices', 25, 'potenti', 'jbeirne2k');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (90, 'faucibus orci luctus', 49, 'massa', 'bmcgucken2l');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (4, 'est et', 20, 'id', 'ccarvill2m');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (90, 'eget', 18, 'lacinia', 'sgurden2n');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (92, 'lorem id ligula', 38, 'diam', 'sbonner2o');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (2, 'quam', 3, 'cubilia', 'ybroggini2p');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (65, 'et magnis', 11, 'dis', 'pstocky2q');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (4, 'molestie', 30, 'suspendisse', 'ptiffney2r');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (22, 'ligula', 50, 'id', 'nbrockwell2s');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (3, 'tortor eu', 38, 'adipiscing', 'fcroce2t');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (30, 'sit amet', 44, 'leo', 'nhembry2u');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (79, 'sociis natoque penatibus', 31, 'vestibulum', 'olegrave2v');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (81, 'commodo', 45, 'sem', 'adurrell2w');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (90, 'vestibulum proin', 38, 'consequat', 'snetti2x');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (68, 'sed', 12, 'purus', 'wholbie2y');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (79, 'consectetuer eget rutrum', 46, 'elit', 'svasyanin2z');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (40, 'nullam molestie', 23, 'justo', 'ijakubiak30');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (98, 'sed vel', 5, 'nulla', 'xchicchetto31');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (80, 'sapien sapien', 7, 'a', 'kduddell32');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (31, 'quis', 13, 'maecenas', 'bmcmeekan33');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (18, 'nam congue risus', 7, 'non', 'askirvane34');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (16, 'turpis', 37, 'vulputate', 'adadge35');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (66, 'tempus vivamus in', 8, 'ante', 'dpardoe36');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (56, 'justo sollicitudin', 0, 'suspendisse', 'rtarbox37');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (80, 'ultrices phasellus id', 20, 'sodales', 'vmaudling38');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (90, 'at diam nam', 21, 'orci', 'amurrigans39');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (50, 'morbi vel', 2, 'tristique', 'kpetche3a');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (53, 'iaculis', 19, 'ut', 'wbeldham3b');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (21, 'arcu adipiscing', 29, 'ultrices', 'rroskeilly3c');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (10, 'varius integer ac', 29, 'elementum', 'ipatrickson3d');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (40, 'odio elementum', 11, 'in', 'tlincke3e');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (47, 'eget orci vehicula', 50, 'nisi', 'acormode3f');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (43, 'tincidunt in leo', 7, 'nibh', 'gblinerman3g');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (51, 'praesent id', 23, 'nisi', 'xstenett3h');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (62, 'ultrices', 36, 'cursus', 'mhusband3i');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (64, 'odio porttitor', 23, 'vel', 'swillimot3j');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (18, 'odio odio elementum', 1, 'suscipit', 'afoulis3k');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (68, 'nulla elit ac', 48, 'nulla', 'alawlan3l');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (46, 'ut erat curabitur', 40, 'purus', 'tscroxton3m');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (31, 'in quam fringilla', 13, 'turpis', 'mpettingill3n');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (29, 'luctus et', 25, 'id', 'gshafe3o');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (37, 'vestibulum sagittis sapien', 48, 'tincidunt', 'kwalding3p');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (45, 'lorem quisque ut', 36, 'blandit', 'vtrump3q');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (34, 'accumsan', 35, 'quam', 'cmellem3r');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (46, 'felis ut at', 19, 'pede', 'mpleager3s');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (40, 'ultricies', 35, 'sollicitudin', 'ifausset3t');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (14, 'eget rutrum at', 5, 'arcu', 'rmacturlough3u');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (33, 'eu orci mauris', 1, 'sapien', 'tmullally3v');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (36, 'orci', 38, 'penatibus', 'nleas3w');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (67, 'habitasse platea dictumst', 31, 'vivamus', 'nlidstone3x');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (22, 'nullam', 36, 'suspendisse', 'arains3y');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (97, 'erat eros', 17, 'in', 'dhadcock3z');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (4, 'lectus pellentesque', 46, 'congue', 'jmcneilly40');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (94, 'turpis adipiscing', 9, 'duis', 'rvidineev41');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (9, 'mauris sit', 4, 'vestibulum', 'jdisbrey42');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (14, 'tellus nulla', 19, 'facilisi', 'smalbon43');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (62, 'vulputate justo in', 41, 'vel', 'lmcgettrick44');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (43, 'in', 4, 'pulvinar', 'dshuttle45');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (98, 'elit sodales', 16, 'id', 'aaland46');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (71, 'erat tortor', 28, 'sit', 'sbrunke47');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (72, 'pulvinar sed nisl', 29, 'id', 'mommundsen48');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (61, 'sed', 37, 'ipsum', 'gwillard49');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (53, 'neque', 32, 'molestie', 'zlidington4a');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (54, 'quam', 45, 'fringilla', 'jtilbey4b');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (88, 'interdum in ante', 9, 'sagittis', 'easson4c');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (86, 'nascetur', 29, 'sapien', 'arundle4d');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (51, 'at nulla suspendisse', 8, 'molestie', 'ddrillingcourt4e');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (64, 'sapien in sapien', 14, 'semper', 'dmaskell4f');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (14, 'in consequat ut', 8, 'cras', 'gsmerdon4g');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (27, 'imperdiet sapien urna', 38, 'amet', 'araddan4h');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (27, 'rutrum', 42, 'pharetra', 'gcarson4i');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (48, 'eget rutrum at', 40, 'ultrices', 'gplumtree4j');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (69, 'justo morbi', 27, 'lectus', 'scapell4k');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (42, 'varius integer ac', 23, 'adipiscing', 'bcunningham4l');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (78, 'in sagittis dui', 32, 'porta', 'cheadington4m');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (85, 'quam sollicitudin', 22, 'morbi', 'cgages4n');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (33, 'lacinia sapien', 47, 'pellentesque', 'rchomiszewski4o');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (40, 'vivamus vestibulum', 2, 'pretium', 'sswarbrick4p');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (26, 'mus etiam', 7, 'egestas', 'dascroft4q');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (11, 'lacinia', 9, 'sapien', 'ilumm4r');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (21, 'massa', 38, 'duis', 'vtalkington4s');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (26, 'lorem ipsum', 31, 'ut', 'sshera4t');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (53, 'interdum mauris non', 47, 'tristique', 'kdalmon4u');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (38, 'orci pede venenatis', 39, 'dui', 'dramos4v');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (30, 'tristique tortor', 39, 'in', 'jtethacot4w');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (9, 'sit amet', 18, 'in', 'apetrazzi4x');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (83, 'commodo', 18, 'mauris', 'krault4y');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (50, 'nulla nunc', 31, 'nam', 'lglyn4z');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (51, 'aenean auctor', 4, 'vivamus', 'mhempel50');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (35, 'felis', 22, 'et', 'vbranca51');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (68, 'rhoncus dui', 17, 'sed', 'hjentgens52');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (71, 'sit amet', 3, 'mauris', 'ebasant53');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (9, 'faucibus orci luctus', 37, 'non', 'sglanville54');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (2, 'odio', 36, 'aenean', 'adantesia55');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (38, 'habitasse platea dictumst', 37, 'proin', 'lboskell56');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (95, 'placerat praesent', 15, 'eu', 'lodom57');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (69, 'libero', 10, 'amet', 'kdielhenn58');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (22, 'vestibulum sit', 49, 'purus', 'sfernez59');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (75, 'posuere', 41, 'a', 'jgreenshiels5a');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (77, 'rutrum', 49, 'vel', 'fnormabell5b');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (50, 'libero rutrum ac', 7, 'pharetra', 'tgannan5c');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (91, 'vestibulum', 45, 'nisi', 'vmain5d');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (37, 'eget orci vehicula', 16, 'turpis', 'hbeven5e');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (66, 'sit amet', 2, 'lacus', 'dhutchin5f');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (66, 'at nunc', 12, 'posuere', 'mdorrell5g');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (48, 'mi', 30, 'in', 'ncardis5h');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (6, 'quam sapien varius', 44, 'non', 'nfurby5i');
insert into klasa (numer_k, grupy, ilosc_godzin, dni_wolne, wychowawca) values (78, 'pulvinar nulla pede', 9, 'erat', 'rbloxsum5j');
